# Generated by Django 2.0.4 on 2018-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rd_related_to_shares',
            name='Is_BasicSet',
        ),
        migrations.RemoveField(
            model_name='rd_related_to_shares',
            name='Is_Called_Second',
        ),
        migrations.AddField(
            model_name='rd_related_to_shares',
            name='RD_load_balance_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rd_related_to_shares',
            name='Should_be_updated_now',
            field=models.BooleanField(default=True),
        ),
    ]
