# Generated by Django 2.0.4 on 2018-04-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0002_auto_20180427_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketstatus',
            name='Max_Task',
            field=models.IntegerField(default=4),
        ),
    ]
