# Generated by Django 2.0.4 on 2018-04-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0003_marketstatus_max_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Share_Category', models.IntegerField(default=1)),
                ('Share_Code', models.CharField(max_length=100)),
                ('Share_Name', models.CharField(max_length=100)),
                ('Is_feasible', models.BooleanField(default=True)),
                ('spk', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Top_Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Share_Category', models.IntegerField(default=0)),
                ('Share_Code', models.CharField(max_length=100)),
                ('Share_Name', models.CharField(max_length=100)),
                ('Is_feasible', models.BooleanField(default=True)),
                ('spk', models.IntegerField(default=0)),
            ],
        ),
    ]
