# Generated by Django 2.0.4 on 2018-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0004_top_coins_top_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_coins',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='top_shares',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='top_coins',
            name='Share_Code',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='top_shares',
            name='Share_Code',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
