# Generated by Django 2.0.4 on 2018-04-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0005_auto_20180427_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Top_Shares',
            new_name='Top_Kospi',
        ),
    ]
