# Generated by Django 2.0.4 on 2018-04-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0006_auto_20180428_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Kosdq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Share_Category', models.IntegerField(default=10)),
                ('Share_Code', models.CharField(default='a', max_length=100)),
                ('Share_Name', models.CharField(max_length=100)),
                ('Is_feasible', models.BooleanField(default=True)),
                ('spk', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
            ],
        ),
    ]
