# Generated by Django 2.0.4 on 2018-04-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0007_top_kosdq'),
    ]

    operations = [
        migrations.CreateModel(
            name='share_chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spk', models.IntegerField(default=0)),
                ('Share_Code', models.CharField(default='a', max_length=20)),
                ('Chart_Dict', models.TextField(default='')),
                ('StandardDate', models.IntegerField(default=0)),
                ('Should_be_updated_now', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='top_coins',
            name='Share_Name',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
