# Generated by Django 2.0.4 on 2018-04-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0008_auto_20180428_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='share_chart',
            name='Share_Category',
            field=models.IntegerField(default=0),
        ),
    ]
