# Generated by Django 2.0.4 on 2018-04-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0009_share_chart_share_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share_chart',
            name='Chart_Dict',
            field=models.TextField(default='{}'),
        ),
    ]
