# Generated by Django 2.0.4 on 2018-04-30 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0010_auto_20180428_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=50, unique=True)),
                ('admin_pw', models.CharField(max_length=500)),
                ('bank_id', models.CharField(max_length=100)),
                ('admin_pn', models.CharField(max_length=100, null=True)),
                ('admin_bank_name', models.CharField(max_length=50)),
                ('admin_name', models.CharField(max_length=50)),
                ('profit_ratio', models.FloatField(default=0.3)),
                ('grant', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '파트너, 관리자 목록',
            },
        ),
        migrations.CreateModel(
            name='DomainList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hts_backend.admins')),
            ],
        ),
        migrations.CreateModel(
            name='M_P_managementList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hts_backend.admins')),
            ],
        ),
    ]
