# Generated by Django 2.0.4 on 2018-05-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0011_admins_domainlist_m_p_managementlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketstatus',
            name='OVNFee',
            field=models.FloatField(default=0.01),
        ),
    ]
