# Generated by Django 2.0.4 on 2018-05-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0013_auto_20180501_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='내용을 입력 하세요', max_length=250)),
                ('contents', models.TextField(default='내용을 입력 하세요')),
                ('is_pop', models.BooleanField(default=False)),
            ],
        ),
    ]
