# Generated by Django 2.0.4 on 2018-05-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0015_granttreestructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.CharField(default='a', max_length=200)),
                ('is_used', models.BooleanField(default=False)),
                ('admin_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hts_backend.admins')),
            ],
        ),
        migrations.CreateModel(
            name='M_Out_Q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqMoment', models.DateTimeField(auto_created=True, auto_now=True)),
                ('moneyQuant', models.IntegerField(default=0)),
                ('admin_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hts_backend.admins')),
            ],
        ),
    ]
