# Generated by Django 2.0.4 on 2018-05-01 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0016_domainq_m_out_q'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainlist',
            name='domain',
            field=models.CharField(default='내용을 입력 하세요', max_length=200),
        ),
        migrations.AddField(
            model_name='domainlist',
            name='dtime',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domainlist',
            name='p_name',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='domainlist',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='m_p_managementlist',
            name='choolgeum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='m_p_managementlist',
            name='dtime_jeongsan',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='m_p_managementlist',
            name='jeongsan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='m_p_managementlist',
            name='sonic',
            field=models.IntegerField(default=0),
        ),
    ]
