# Generated by Django 2.0.4 on 2018-05-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0017_auto_20180501_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_out_q',
            name='reqMoment',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
