# Generated by Django 2.0.4 on 2018-05-01 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0018_auto_20180501_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit_Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('day_In', models.IntegerField(default=0)),
                ('day_Out', models.IntegerField(default=0)),
                ('day_Profit', models.IntegerField(default=0)),
                ('sonic_d', models.IntegerField(default=0)),
                ('admin_in_d', models.IntegerField(default=0)),
                ('admin_out_d', models.IntegerField(default=0)),
                ('partner_jeongsan_d', models.IntegerField(default=0)),
                ('new_user_d', models.IntegerField(default=0)),
                ('yesterday', models.DateTimeField(default=datetime.datetime(2018, 5, 2, 4, 26, 13, 653295))),
                ('yesterday_In', models.IntegerField(default=0)),
                ('yesterday_Out', models.IntegerField(default=0)),
                ('yesterday_Profit', models.IntegerField(default=0)),
                ('sonic_y', models.IntegerField(default=0)),
                ('admin_in_y', models.IntegerField(default=0)),
                ('admin_out_y', models.IntegerField(default=0)),
                ('partner_jeongsan_y', models.IntegerField(default=0)),
                ('new_user_y', models.IntegerField(default=0)),
                ('daybefore', models.DateTimeField(default=datetime.datetime(2018, 5, 2, 4, 26, 13, 653295))),
                ('daybefore_In', models.IntegerField(default=0)),
                ('daybefore_Out', models.IntegerField(default=0)),
                ('daybefore_Profit', models.IntegerField(default=0)),
                ('sonic_db', models.IntegerField(default=0)),
                ('admin_in_db', models.IntegerField(default=0)),
                ('admin_out_db', models.IntegerField(default=0)),
                ('partner_jeongsan_db', models.IntegerField(default=0)),
                ('new_user_db', models.IntegerField(default=0)),
                ('monthNow', models.CharField(default='None', max_length=10)),
                ('monthNow_In', models.IntegerField(default=0)),
                ('monthNow_Out', models.IntegerField(default=0)),
                ('monthNow_Profit', models.IntegerField(default=0)),
                ('sonic_m', models.IntegerField(default=0)),
                ('admin_in_m', models.IntegerField(default=0)),
                ('admin_out_m', models.IntegerField(default=0)),
                ('partner_jeongsan_m', models.IntegerField(default=0)),
                ('new_user_m', models.IntegerField(default=0)),
                ('monthLate', models.CharField(default='None', max_length=10)),
                ('monthLate_In', models.IntegerField(default=0)),
                ('monthLate_Out', models.IntegerField(default=0)),
                ('monthLate_Profit', models.IntegerField(default=0)),
                ('sonic_ml', models.IntegerField(default=0)),
                ('admin_in_ml', models.IntegerField(default=0)),
                ('admin_out_ml', models.IntegerField(default=0)),
                ('partner_jeongsan_ml', models.IntegerField(default=0)),
                ('new_user_ml', models.IntegerField(default=0)),
            ],
        ),
    ]
