# Generated by Django 2.0.4 on 2018-05-02 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0019_profit_stat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profit',
            old_name='Total_Realized_Profit_Except_Fees',
            new_name='Total_Realized_Profit',
        ),
        migrations.AlterField(
            model_name='profit_stat',
            name='daybefore',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 17, 35, 12, 257953)),
        ),
        migrations.AlterField(
            model_name='profit_stat',
            name='yesterday',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 17, 35, 12, 257953)),
        ),
    ]
