# Generated by Django 2.0.4 on 2018-05-02 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0022_auto_20180502_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_M_IO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtime_jeongsan', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('Order', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField(default=0)),
                ('user_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hts_backend.User_In')),
            ],
        ),
        migrations.AlterField(
            model_name='profit_stat',
            name='daybefore',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 22, 40, 52, 775148)),
        ),
        migrations.AlterField(
            model_name='profit_stat',
            name='yesterday',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 22, 40, 52, 775148)),
        ),
    ]
