# Generated by Django 2.0.4 on 2018-05-02 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0023_auto_20180502_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_m_io',
            name='dtime_jeongsan',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='m_p_managementlist',
            name='dtime_jeongsan',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profit_stat',
            name='daybefore',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 22, 45, 33, 338494)),
        ),
        migrations.AlterField(
            model_name='profit_stat',
            name='yesterday',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 22, 45, 33, 338494)),
        ),
    ]
