# Generated by Django 2.0.4 on 2018-05-02 14:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0025_auto_20180502_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_in',
            name='total_access_time',
        ),
        migrations.AddField(
            model_name='user_in',
            name='init_signed_in_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profit_stat',
            name='daybefore',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 23, 22, 50, 152217)),
        ),
        migrations.AlterField(
            model_name='profit_stat',
            name='yesterday',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 23, 22, 50, 152217)),
        ),
    ]
