# Generated by Django 2.0.4 on 2018-05-02 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0026_auto_20180502_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit_stat',
            name='TOTAL_IN_BY_NOW',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profit_stat',
            name='TOTAL_OUT_BY_NOW',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profit_stat',
            name='daybefore',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 2, 16, 9, 259462)),
        ),
        migrations.AlterField(
            model_name='profit_stat',
            name='yesterday',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 2, 16, 9, 259462)),
        ),
    ]
