# Generated by Django 2.0.4 on 2018-05-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0032_auto_20180503_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit_Stat_Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('day_In', models.IntegerField(default=0)),
                ('day_Out', models.IntegerField(default=0)),
                ('users_total_yest', models.IntegerField(default=0)),
                ('user_total_today', models.IntegerField(default=0)),
                ('profit_ratio', models.FloatField(default=0)),
                ('sonic', models.IntegerField(default=0)),
                ('commission', models.IntegerField(default=0)),
                ('partner_out', models.IntegerField(default=0)),
                ('jeongsan_today', models.IntegerField(default=0)),
                ('regular_total_jeongsan', models.IntegerField(default=0)),
                ('admin_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hts_backend.admins')),
            ],
            options={
                'verbose_name': '파트너 수익 통계',
            },
        ),
        migrations.RemoveField(
            model_name='m_p_managementlist',
            name='choolgeum',
        ),
        migrations.RemoveField(
            model_name='m_p_managementlist',
            name='sonic',
        ),
        migrations.AddField(
            model_name='m_p_managementlist',
            name='profit_ratio',
            field=models.FloatField(default=0),
        ),
    ]
