# Generated by Django 2.0.4 on 2018-05-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0033_auto_20180503_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '공지사항'},
        ),
        migrations.AddField(
            model_name='marketstatus',
            name='ExchangeRate_USD',
            field=models.IntegerField(default=1070),
        ),
    ]
