# Generated by Django 2.0.4 on 2018-05-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0037_remove_user_in_is_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_in',
            name='is_accessed',
            field=models.BooleanField(default=False),
        ),
    ]
