# Generated by Django 2.0.4 on 2018-05-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0038_user_in_is_accessed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_in',
            name='is_accessed',
        ),
    ]
