# Generated by Django 2.0.4 on 2018-05-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0039_remove_user_in_is_accessed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='granttreestructure',
            name='admin_refer_idx',
        ),
        migrations.AddField(
            model_name='granttreestructure',
            name='admin_refer_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
