# Generated by Django 2.0.4 on 2018-05-04 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0040_auto_20180504_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='granttreestructure',
            name='admin_refer_id',
        ),
        migrations.AddField(
            model_name='granttreestructure',
            name='admin_refer_idx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_refer_idx', to='hts_backend.admins'),
        ),
    ]
