# Generated by Django 2.0.4 on 2018-05-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0041_auto_20180504_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_order_done',
            name='Order_Date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
