# Generated by Django 2.0.4 on 2018-05-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0042_auto_20180504_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_order_done',
            name='Done_Date',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
