# Generated by Django 2.0.4 on 2018-05-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0044_auto_20180507_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketstatus',
            name='LoanFee',
            field=models.FloatField(default=0.02),
        ),
    ]
