# Generated by Django 2.0.4 on 2018-05-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0045_marketstatus_loanfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketstatus',
            name='IpTcpAdr',
            field=models.CharField(default='192.168.35.60:8000', max_length=200),
        ),
    ]
