# Generated by Django 2.0.4 on 2018-05-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0046_marketstatus_iptcpadr'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit_withdraw_order_done_list',
            name='user_id',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='loan_order_done',
            name='user_id',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
