# Generated by Django 2.0.4 on 2018-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0047_auto_20180509_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
