# Generated by Django 2.0.4 on 2018-05-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0048_transaction_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Share_Name',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
