# Generated by Django 2.0.4 on 2018-05-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0050_auto_20180513_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainlist',
            name='admin_idx',
        ),
        migrations.AddField(
            model_name='domainlist',
            name='admin_id',
            field=models.CharField(default='아이디를 입력 하세요', max_length=50),
        ),
        migrations.AlterField(
            model_name='domainlist',
            name='p_name',
            field=models.CharField(default='파트너 이름을 입력 하세요', max_length=100),
        ),
    ]
