# Generated by Django 2.0.4 on 2018-05-15 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0052_auto_20180516_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='granttreestructure',
            options={'verbose_name': '파트너 열람 권한 표'},
        ),
        migrations.AlterField(
            model_name='granttreestructure',
            name='admin_idx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hts_backend.admins'),
        ),
    ]
