# Generated by Django 2.0.4 on 2018-05-27 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0053_auto_20180516_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profit_stat_partner',
            old_name='user_total_today',
            new_name='users_total_today',
        ),
    ]
