# Generated by Django 2.0.4 on 2018-05-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0054_auto_20180526_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin_m_io',
            options={'verbose_name': '관리자 입출금 테이블'},
        ),
        migrations.AddField(
            model_name='user_in',
            name='behave_type',
            field=models.IntegerField(default=0),
        ),
    ]
