# Generated by Django 2.0.4 on 2018-06-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hts_backend', '0055_auto_20180530_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_p_managementlist',
            name='admin_id',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='profit_stat_partner',
            name='admin_id',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
